[build]
  publish = "frontend"
  command = ""

# Optional: Redirect API paths to a hosted backend domain if you quiser roteamento bonito
# [[redirects]]
#   from = "/api/*"
#   to = "https://SEU_BACKEND/render/upload_json"
#   status = 200
