services:
- type: web
  name: verificar-xml-backend
  env: python
  plan: free
  buildCommand: "pip install -r backend/requirements.txt"
  startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
  autoDeploy: true
  healthCheckPath: /ping
  envVars:
    - key: PYTHON_VERSION
      value: 3.11
